name: CivFactions
version: 0.1
author: KingVictoria
main: com.gmail.therealkingvictoria.CivFactions
commands:
 testcreate:
  description: creates a test faction
  usage: /testcreate
 testdelete:
  description: deletes all factions
  usage: /testdelete